### ISSUE TITLE
Trying to access the global window object - Error: Cannot find module "window"

### ISSUE THREAD

**Issue by happyvig** [webpack-contrib/imports-loader#26]
Hi.,
I am trying to access **window** object inside **main.js file** by injecting it from **index.js** via imports-loader syntax and webpack-ing it.

```
ERROR in ./~/imports-loader?global=window!./main.js
Module not found: Error: Cannot resolve module 'window' in C:\Users\user\Desktop\webpack-dummy
 @ ./~/imports-loader?global=window!./main.js 2:13-30
C:\Users\user\Desktop\webpack-dummy\dist\bundle.js:55
        var global = __webpack_require__(!(function webpackMissingModule() { var e = new Error("Cannot find module \"window\""); e.code = 'M
ODULE_NOT_FOUND'; throw e; }()));                  ^

Error: Cannot find module "window"
```

```
C:\Users\user\Desktop\webpack-dummy\dist\bundle.js:62
        }.call(window));              
                 ^
ReferenceError: window is not defined
```

```
C:\Users\user\Desktop\webpack-dummy\dist\bundle.js:55
        var global = window;
                            ^
ReferenceError: window is not defined
```

**index.js**
`Tried this : require('imports?global=window!./main.js');` 
`Tried this: require('imports?this=>window!./main.js');`
`Tried this : require('imports?global=>window!./main.js');`

**main.js**

```
module.exports = ((function () {
    window.myName = "Clark Kent";
    console.log(window.myName);
    return {};
})());
```

**webpack.config.js**

```
module.exports = {
    entry: "./index.js",
    output: {
        path: 'dist',
        filename: "bundle.js"
    },
    resolve: {
        extensions: ['', '.js']
    },
    target: "web"    
};
```

**Comment by SpaceK33z** [comment]
Could you try again with `imports-loader@0.7.0`?

**Comment by rennitbaby** [comment]
Any updates on this problem? Did it work with import-loader@0.7.0? 

I have a similar problem in importing angularjs 1.5.11, whereas the angular script from node_module is as follows, and window is not defined when webpack bundles the file. 

(function(window){
//angular code
})(window) <-- this is not defined when webpack bundles the file. 

even when webpack.config.target = 'web'

Can anyone shed some light on this issue?

**Comment by Ziden** [comment]
same issue here

**Comment by cybermerlin** [comment]
trouble is actual

**Comment by nidhinmk** [comment]
Is there a way to not to comment the imports and make it work?

**Comment by evilebottnawi** [comment]
Fixed
