### ISSUE TITLE
Allow "import" instead of "require"

### ISSUE THREAD

**Issue by fstanis** [webpack-contrib/imports-loader#60]
In my project, I use `import` rather than `require` - this means that using `imports-loader` makes me end up with files that have both `import` and `require`.

Normally, this wouldn't be an issue, however, it seems Webpack handles these two slightly differently - namely, `import` seems to take precedence over `require` - and there are modules like babel-polyfill which are designed to be the first thing imported, which is causing me trouble (I'm aware this is not the best example, as babel-polyfill can be imported as an entry, but didn't want to digress too much).

Perhaps more importantly, `import` tends to be more versatile, allowing things like importing a single export.

Any objections to adding an extra syntax (e.g. "=+", with "something=+module" resulting in `import something from "module"` and "{e}=+module" resulting in `import {e} from "module"`) that would cause `imports-loader` to produce `import` syntax rather than require? Happy to do a PR for that.

**Comment by michael-ciniawsky** [comment]
We should update this and release a new major version with support for `webpack >= v2.0.0 || v3.0.0` only, dropping the use of `require` in favor of the ECMAScript Module Standards (`import/import()`). Any help and PR's welcome :)

**Comment by fstanis** [comment]
Ah, so the idea is to drop `require` all together? I'm fine with that. :+1: 

That said, there are a few things that are worth clarifying first:

-   Should 1.0.0 remain backwards compatible? Specifically, `this=module` and `a.b.c=module` both seems clunky to handle with `import` (my best idea is to import into a temporary variable, e.g. "__importsLoader_this" and "__importsLoader_a_b_c" and use that).
-   On that note, should the default for `name=module` be `import name from "module"` or `import * as name from "module"`? The latter is probably more in-line with what `require` does, but the former is, well, more likely what's expected.

**Comment by michael-ciniawsky** [comment]
> Ah, so the idea is to drop require all together?

If possible yes, It depends if a smooth upgrade to `import` is possible, I didn't tried anything out yet and there a definitely differences between `require()/import`, which could eventually become challenging here and there :)

> Should 1.0.0 remain backwards compatible?

It's semver major so in general no 😛, but the functionality && use cases should still be satisfied by the loader without to much difference, besides the required changes and what could be made nicer. This loader is pretty outdated atm (`webpack v1.0.0`), it's even necessary to 'redesign' the options interface to work with `webpack >= v2.0.0`  `loader.options` syntax

**webpack.config.js**
```js
{
   loader: 'imports-loader'
   // Pseudo
   options: {
     $: 'jQuery'
     module: require.resolve('module')
     ...
   }
}
```

There is plenty of room for refactors :)

> Specifically, this=module and a.b.c=module both seems clunky to handle with import (my best idea is to import into a temporary variable, e.g. "__importsLoader_this" and "__importsLoader_a_b_c" and use that).

Something like that yes, but I need to follow suit here tbh :)

> On that note, should the default for name=module be import name from "module" or import * as name from "module"? The latter is probably more in-line with what require does, but the former is, well, more likely what's expected.

`import * as module from 'module'`  I think is the best choice to start with, this my require an `loader.option` though

**Comment by kyleholzinger** [comment]
has this been updated yet? I don't think I can use this with webpack 4, I'm getting a bunch of these compilation errors and warnings:
```
Module build failed: SyntaxError: 'import' and 'export' may only appear at the top level
```

**Comment by Backfighter** [comment]
Checkout the [inject-imports-loader](https://github.com/Backfighter/inject-imports-loader) I wrote. It was specifically made to support the new import syntax while not having to remain backwards compatible with the configuration format imports-loader uses.
